# -*- coding: utf-8 -*-
"""churn_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPxiRsMBHG2DsAVI1PVqjY02XfHmg1dt
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
pickle_in = open('xgb_model.pkl','rb')
xgb_model = pickle.load(pickle_in)
def predic(state,area_code,account_length,voice_plan,voice_messages,intl_plan,
           intl_mins,intl_calls,intl_charge,day_mins,day_calls,day_charge,eve_mins
           ,eve_calls,eve_charge,night_mins,night_calls,night_charge,customer_calls):
    prediction = xgb_model.predict([[state,area.code,account.length,voice.plan,voice.messages,intl.plan,
           intl.mins,intl.calls,intl.charge,day.mins,day.calls,day.charge,eve.mins
           ,eve.calls,eve.charge,night.mins,night.calls,night.charge,customer.calls]])
    print(prediction)
    return prediction
def main():
  st.title("churn prediciton")
  state=st.text_input("state")
  area_code=st.text_input("Area.code")
  account_length=st.text_input("account.length")
  voice_plan=st.text_input("voice.plan")
  voice_messages=st.text_input("voice.messages")
  intl_plan=st.text_input("intl.plan")
  intl_mins=st.text_input("intl.mins")
  intl_calls=st.text_input("intl.calls")
  intl_charge=st.text_input("intl.charge")
  day_mins=st.text_input("day.mins")
  day_calls=st.text_input("day.calls")
  day_charge=st.text_input("day.charge")
  eve_mins=st.text_input("eve.mins")
  eve_calls=st.text_input("eve.calls")
  eve_charge=st.text_input("eve.charge")
  night_mins=st.text_input("night.mins")
  night_calls=st.text_input("night.calls")
  night_charge=st.text_input("night.charge")
  customer_calls=st.text_input("customer.calls")
  result=""
  if st.button("predict"):
    result=predic(state,area_code,account_length,voice_plan,voice_messages,intl_plan,
           intl_mins,intl_calls,intl_charge,day_mins,day_calls,day_charge,eve_mins
           ,eve_calls,eve_charge,night_mins,night_calls,night_charge,customer_calls)
  st.success('The output is {}'.format(result))
if __name__=='__main__':
  main()